--- # Loops YAML Files
- hosts: dev,prod
  user: ubuntu
  become: yes
  connection: ssh
  tasks:
    - name: Create multiple users
      user:
        name: "{{ item }}"
        state: present
      loop:
        - avinash
        - parth
